image: node:8.5.0 # can be upgraded, depending on your node version used

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - install
  - build
  - deploy

install:
  stage: install
  script:
    - npm install
  cache:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  cache:
    paths:
      -  build/
  artifacts:
    paths:
    - build/
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - scp  -r build/*  root@app.tethyr.com:/var/www/recommend.tethyr.com/html/
  dependencies:
    - build
  only:
    - master
